---

- name: Invoke Plan Creation
  ansible.builtin.include_tasks:
    file: create.yml
  when: mtv_plans_action == 'create'

- name: Invoke Plan Archival
  ansible.builtin.include_tasks:
    file: archive.yml
  when: mtv_plans_action == 'archive'

- name: Invoke Plan Deletion
  ansible.builtin.include_tasks:
    file: delete.yml
  when: mtv_plans_action == 'delete'
...
