---
- name: build_credentials | Apply credential type toggle
  ansible.builtin.set_fact:
    aap_seed_controller_credential_types: >-
      {{ aap_seed_controller_credential_types
         if (aap_seed_credential_types_create | bool) and
            (groups[aap_seed_source_inventory_group] | default([]) | length > 0)
         else [] }}

- name: build_credentials | Initialize credential list
  ansible.builtin.set_fact:
    aap_seed_controller_credentials: []
  when: aap_seed_credentials_create | bool

- name: build_credentials | Build source environment credentials
  ansible.builtin.set_fact:
    aap_seed_controller_credentials: >-
      {{ aap_seed_controller_credentials +
         [lookup('template', 'source_credential.yml.j2')
         | ansible.builtin.from_yaml] }}
  loop: "{{ groups[aap_seed_source_inventory_group] | default([]) }}"
  loop_control:
    loop_var: __aap_seed_host_name
    label: "{{ __aap_seed_host_name }}"
  no_log: "{{ aap_seed_secure_logging }}"
  when: aap_seed_credentials_create | bool
  vars:
    __aap_seed_vars: "{{ hostvars[__aap_seed_host_name] }}"

- name: build_credentials | Build target cluster credentials
  ansible.builtin.set_fact:
    aap_seed_controller_credentials: >-
      {{ aap_seed_controller_credentials +
         [lookup('template', 'target_credential.yml.j2')
         | ansible.builtin.from_yaml] }}
  loop: "{{ groups[aap_seed_target_inventory_group] | default([]) }}"
  loop_control:
    loop_var: __aap_seed_host_name
    label: "{{ __aap_seed_host_name }}"
  no_log: "{{ aap_seed_secure_logging }}"
  when: aap_seed_credentials_create | bool
  vars:
    __aap_seed_vars: "{{ hostvars[__aap_seed_host_name] }}"

- name: build_credentials | Build Git credential for SCM project
  ansible.builtin.set_fact:
    aap_seed_controller_credentials: >-
      {{ aap_seed_controller_credentials +
         [lookup('template', 'git_credential.yml.j2')
         | ansible.builtin.from_yaml] }}
  no_log: "{{ aap_seed_secure_logging }}"
  when:
    - aap_seed_credentials_create | bool
    - aap_seed_project_credential | default('', true) | length > 0

- name: build_credentials | Disable credentials when toggle is off
  ansible.builtin.set_fact:
    aap_seed_controller_credentials: []
    aap_seed_controller_credential_types: []
  when: not (aap_seed_credentials_create | bool)
...
