---
- name: sync_project | Create or update the project in AAP
  ansible.builtin.include_role:
    name: infra.aap_configuration.controller_projects
  vars:
    controller_projects: "{{ aap_seed_controller_projects }}" # noqa: var-naming[no-role-prefix]

- name: sync_project | Sync project from SCM and wait for completion
  ansible.builtin.include_role:
    name: infra.aap_configuration.controller_project_update
  vars:
    controller_project_update:
      - name: "{{ aap_seed_project_name }}"
        organization: "{{ aap_seed_org_name }}"
        wait: true
        timeout: "{{ aap_seed_project_sync_timeout }}"
...
