---
- name: _cleanup_operators | Remove operators in reverse order
  ansible.builtin.include_tasks:
    file: _cleanup_operator_item.yml
  loop: "{{ ocp_cleanup_operators | reverse | list }}"
  loop_control:
    loop_var: _ocp_cleanup_operator_name
    label: "{{ _ocp_cleanup_operator_name }}"
  when: _ocp_cleanup_operator_name in ocp_cleanup_operator_definitions
...
