---
- name: Remove MTV CRDs
  ansible.builtin.include_tasks:
    file: _cleanup_mtv_crds.yml
  loop: "{{ ocp_cleanup_mtv_crd_kinds }}"
  loop_control:
    loop_var: _ocp_cleanup_crd
    label: "{{ _ocp_cleanup_crd.kind }}"
  when: >-
    (ocp_cleanup_mtv_migrations_remove | bool and _ocp_cleanup_crd.kind == 'Migration') or
    (ocp_cleanup_mtv_plans_remove | bool and _ocp_cleanup_crd.kind == 'Plan') or
    (ocp_cleanup_mtv_maps_remove | bool and _ocp_cleanup_crd.kind in ['NetworkMap', 'StorageMap']) or
    (ocp_cleanup_mtv_providers_remove | bool and _ocp_cleanup_crd.kind == 'Provider')

- name: Remove MTV secrets
  ansible.builtin.include_tasks:
    file: _cleanup_mtv_secrets.yml
  when: ocp_cleanup_mtv_secrets_remove | bool

- name: Remove migrated VMs and PVCs
  ansible.builtin.include_tasks:
    file: _cleanup_migrated_vms.yml
  when: ocp_cleanup_migrated_vms_remove | bool

- name: Remove target namespaces
  ansible.builtin.include_tasks:
    file: _cleanup_namespaces.yml
  when: ocp_cleanup_target_namespaces_remove | bool

- name: Remove operators
  ansible.builtin.include_tasks:
    file: _cleanup_operators.yml
  when: ocp_cleanup_operators_remove | bool
...
