---
- name: Remove seeded AAP content from Migration Factory instance
  hosts: migration_aap
  connection: local
  gather_facts: false

  roles:
    - role: infra.openshift_virtualization_migration.aap_cleanup
      vars:
        aap_cleanup_job_history_purge: true
...
