---
- name: Run cluster healthchecks
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Include cluster_healthcheck role
      ansible.builtin.import_role:
        name: infra.openshift_virtualization_migration.cluster_healthcheck
...
