---

- name: Deploy an Ansible Automation Platform credential to the target OpenShift cluster
  hosts: "{{ utility_clusters | default('migration_clusters:aap_clusters') }}"
  gather_facts: false
  connection: local
  tasks:
    - name: Invoke utility_aap_deploy role
      ansible.builtin.include_role:
        name: infra.openshift_virtualization_migration.utility_aap_deploy
      when:
        - >-
          inventory_hostname in groups['aap_clusters'] | default([]) or
          (inventory_hostname in groups['migration_clusters'] and
          hostvars[inventory_hostname]['install_aap'] | default(false) | bool)
...
