---

- name: Generate a credential for the target OpenShift cluster
  hosts: "{{ utility_clusters | default('migration_clusters') }}"
  gather_facts: false
  tasks:
    - name: Invoke utility_openshift_target_credential role
      ansible.builtin.include_role:
        name: infra.openshift_virtualization_migration.utility_openshift_target_credential
        apply:
          delegate_to: localhost
...
