---
- name: Configure MTV Providers on OpenShift
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create MTV provider for source-target pair
      ansible.builtin.import_role:
        name: infra.openshift_virtualization_migration.mtv_provider
...
